// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrB1mBU2Fle6Ik2L6Rp0D4gAjX3MMzDE',
    appId: '1:708504279479:web:3e671cf495d9ae17de3032',
    messagingSenderId: '708504279479',
    projectId: 'grdfapp',
    authDomain: 'grdfapp.firebaseapp.com',
    storageBucket: 'grdfapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVz1yRqVCl5NZS4q1pFsWiRz6a_NHBzk',
    appId: '1:708504279479:android:46bdd06918532bb6de3032',
    messagingSenderId: '708504279479',
    projectId: 'grdfapp',
    storageBucket: 'grdfapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvrB1mBU2Fle6Ik2L6Rp0D4gAjX3MMzDE',
    appId: '1:708504279479:web:ad396477c860ebbade3032',
    messagingSenderId: '708504279479',
    projectId: 'grdfapp',
    authDomain: 'grdfapp.firebaseapp.com',
    storageBucket: 'grdfapp.firebasestorage.app',
  );

}